name: Kiln
options:
  bundleIdPrefix: com.isabelgwara
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Debug
settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: 1
targets:
  Kiln:
    type: application
    platform: iOS
    sources:
      - path: Kiln
        excludes:
          - "**/*.xcassets/AppIcon.appiconset/Contents.json"
    resources:
      - path: Kiln/Assets.xcassets
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.isabelgwara.Kiln
        PRODUCT_NAME: Kiln
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        DEVELOPMENT_TEAM: ""
    info:
      path: Kiln/Info.plist
      properties:
        UIBackgroundModes: []
